dbfilename redis_queue.rdb
dir /home/pranjal/Desktop/finhub_local/erp_stack_v15/config/pids
pidfile /home/pranjal/Desktop/finhub_local/erp_stack_v15/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/pranjal/Desktop/finhub_local/erp_stack_v15/config/redis_queue.acl
